# Generated by Django 5.1 on 2024-08-20 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LotmCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(max_length=100)),
                ('sequence', models.CharField(max_length=50)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lotm_data', to='NovelWiki_app.character')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='NovelWiki_app.novel'),
        ),
        migrations.CreateModel(
            name='ShadowSlaveCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aspect_rank', models.CharField(max_length=100)),
                ('aspect', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=60)),
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_slave_data', to='NovelWiki_app.character')),
            ],
        ),
    ]
